spring:
  application:
    name: discrete-stock
  datasource:
    url: jdbc:mysql://localhost:3306/cofcodb
    username: root
    password: welcome123
server:
  port: 8082
  
trading:
  app: Commodating Tradding software