spring:
  application:
    name: purchase-contract
  datasource:
      url: jdbc:mysql://localhost:3306/cofcodb
      username: root
      password: welcome123

server:
  port: 8081
 

 
trading:
  app: Commodating Tradding software

  